package v3XzZ.mFC;

import net.minecraftforge.common.Configuration;

/**
 * Project: mFC
 * 
 * Class: Identifications
 * 
 * @author v3XzZ
 * @license Lesser GNU Public License v3 (http://www.gnu.org/licenses/lgpl.html)
 * 
 */

public abstract class Identifications {
	
	public static int cornCobFood;
	public static int lettuceFood;
	public static int orangeFood;
	public static int avacadoFood;
	public static int guacamoleFood;
	public static int orangeJuiceFood;
	public static int HamBurgerFood;
	public static int CheeseBurgerFood;
	public static int CheesePieceFood;
	public static int HamburgerBreadFood;
	public static int BottleWaterFood;
	public static int RawHamburgerMeatFood;
	public static int roastPumpkinFood;
	public static int HamburgerMeatFood;
	public static int RawBaconFood;
	public static int BaconFood;
	public static int StripsFood;
	public static int CheeseBaconBurgerFood;
	public static int CupChoklateFood;
	public static int friedEggFood;
	public static int BreadSliceFood;
	public static int EggSandwichFood;
	public static int EggBaconSandwichFood;
	public static int CupTeaFood;
	public static int HotDogRawFood;
	public static int HotDogGrilledFood;
	public static int HotDogFood;
	public static int cornCobCookedFood;
	public static int tomatoFood;
	public static int HotDogKetchupFood;
	public static int PastaSalladFood;
	public static int PastaMeatsauceFood;
	public static int ChickenSalladFood;
	public static int CeasarSalladFood;
	public static int MayonnaiseFood;
	public static int MeatSauceFood;
	public static int MelonJuiceFood;
	public static int AppleJuiceFood;
	public static int BeefJerkyFood;
	public static int ChickenSandwichFood;
	public static int onionFood;
	public static int strawBerryFood;
	public static int raspBerryFood;
	public static int grapesFood;
	public static int paltFood;
	public static int pancakesFood;
	public static int beerFood;
	public static int whiteWineFood;
	public static int redWineFood;
	public static int ChristmasMustFood;
	public static int MakiFood;
	public static int LaxSuchiFood;
	public static int BowlOfRiceFood;
	public static int dogFoodFood;
	public static int chocolateBarFood;
	public static int StrawBerryjamFood;
	public static int RaspBerryjamFood;
	public static int RaspBerryJuiceFood;
	public static int StrawBerryJuiceFood;
	public static int tomatoAndOnionSalladFood;
	public static int macaroniAndCheeseFood;
	public static int porridgeFood;
	public static int gingerBreadFood;
	public static int candyCaneFood;

	
	public static int Saplings;
	public static int ricePlantBlock;
	public static int lettucePlantBlock;
	public static int cornPlantBlock;
	public static int yellowSeedlingBlock;
	public static int redSeedlingBlock;
	public static int tomatoPlantBlock;
	public static int appleBlock;
	public static int avacadoBlock;
	public static int orangeBlock;
	public static int cocoaBlock;
	public static int ApplePieBlock;
	public static int TacoPieBlock;
	public static int ChocolateCakeBlock;
	public static int MeatPieBlock;
	public static int saltBlock;
	public static int cheeseBlock;
	public static int BakeTableBlock;
	public static int onionPlantBlock;
	public static int raspBerryPlantBlock;
	public static int strawBerryPlantBlock;
	public static int GrapeHolderBlock;
	public static int grapesPlantBlock;
	public static int beerKegBlockID;
	public static int wasabiPlantBlock;
	public static int leavesBlock;
//	public static int presentBlock;
	
	
	public static int tomatoSeedsID;
	public static int cornSeedsID;
	public static int pumpkinPieceID;
	public static int roastPumpkinID;
	public static int lettuceSeedsID;
	public static int cornCobID;
	public static int yellowSeedsID;
	public static int redSeedsID;
	public static int cornCobCookedID;
	public static int tomatoID;
	public static int lettuceID;
	public static int orangeID;
	public static int cocoaID;
	public static int avacadoID;
	public static int orangeJuiceID;
	public static int DollarID;
	public static int HamBurgerID;
	public static int CheeseBurgerID;
	public static int CheeseMoldID;
	public static int CheeseMoldMilkID;
	public static int CheeseMoldCheeseID;
	public static int CheeseBlockID;
	public static int CheesePieceID;
	public static int HamburgerBreadID;
	public static int BottleWaterID;
	public static int DrinkingGlassID;
	public static int KnifeID;
	public static int RawHamburgerMeatID;
	public static int HamburgerMeatID;
	public static int RawBaconID;
	public static int BaconID;
	public static int StripsID;
	public static int CheeseBaconBurgerID;
	public static int CupUnburnedID;
	public static int CupID;
	public static int CupChoklateID;
	public static int TeaCanUnburnedID;
	public static int TeaCanID;
	public static int friedEggID;
	public static int BreadSliceID;
	public static int EggSandwichID;
	public static int EggBaconSandwichID;
	public static int CupTeaID;
	public static int ColdTeaCanID;
	public static int HotTeaCanID;
	public static int HotDogRawID;
	public static int HotDogGrilledID;
	public static int HotDogID;
	public static int BucketID;
	public static int bucketWaterID;
	public static int bucketMilkID;
	public static int obsidianPickID;
	public static int obsidianShovelID;
	public static int obsidianAxeID;
	public static int obsidianHoeID;
	public static int obsidianSwordID;
	public static int guacamoleID;
	public static int applesnufkinID;
	public static int orangecoresID;
	public static int avacadonutID;
	public static int ApplePieID;
	public static int TacoPieID;
	public static int ChocolateCakeID;
	public static int MeatPieID;
	public static int AppleJuiceID;
	public static int SaltID;
	public static int PastaID;
	public static int KetchupID;
	public static int PastaMeatsauceID;
	public static int ChickenSalladID;
	public static int HotDogKetchupID;
	public static int MeatSauceID;
	public static int BeefJerkyID;
	public static int ChickenSandwichID;
	public static int CeasarSalladID;
	public static int MayonnaiseID;
	public static int OilID;
	public static int MelonJuiceID;
	public static int PastaSalladID;
	public static int riceSeedsID;
	public static int RiceID;
	public static int WasabiRootID;
	public static int onionID;
	public static int strawBerryID;
	public static int raspBerryID;
	public static int grapesID;
	public static int paltID;
	public static int pancakesID;
	public static int onionSeedsID;
	public static int raspBerrySeedsID;
	public static int strawBerrySeedsID;
	public static int grapeSeedsID;
	public static int beerCupID;
	public static int beerID;
	public static int redWineID;
	public static int whiteWineID;
	public static int ChristmasMustID;
	public static int tallBottleID;
	public static int beerBaseID;
	public static int redWineBaseID;
	public static int whiteWineBaseID;
	public static int ChristmasMustBaseID;
	public static int MakiLongID;
	public static int MakiShortID;
	public static int LaxSuchiID;
	public static int BowlOfRiceID;
	public static int dogFoodID;
	public static int WasabiID;
	public static int jamJarID;
	public static int RaspBerryjamID;
	public static int StrawBerryjamID;
	public static int chocolateBarID;
	public static int RaspBerryJuiceID;
	public static int StrawBerryJuiceID;
	public static int tomatoAndOnionSalladID;
	public static int carrotStewID;
	public static int beefStewID;
	public static int onionStewID;
	public static int beefSoupID;
	public static int carrotStewFood;
	public static int beefStewFood;
	public static int onionStewFood;
	public static int beefSoupFood;
	public static int macaroniAndCheeseID;
	public static int porridgeID;
	public static int MaltID;
	public static int wasabiSeedsID;
	public static int boiledRiceID;
	public static int gingerBreadID;
	public static int candyCaneID;
	public static int forkID;
	
	public static int PlateBlock;
	public static int shelfBlock;
	
	public static void InitID(Configuration config) {
			cornCobFood = config.get("HealAmount", "cornCob", 1).getInt();
			lettuceFood = config.get("HealAmount", "lettuce", 1).getInt();
			orangeFood = config.get("HealAmount", "orange", 2).getInt();
			avacadoFood = config.get("HealAmount", "avacado", 2).getInt();
			guacamoleFood = config.get("HealAmount", "guacamole", 6).getInt();
			orangeJuiceFood = config.get("HealAmount", "orangeJuice", 6).getInt();
			HamBurgerFood = config.get("HealAmount", "HamBurger", 10).getInt();
			CheeseBurgerFood = config.get("HealAmount", "CheeseBurger", 14).getInt();
			CheesePieceFood = config.get("HealAmount", "CheesePiece", 1).getInt();
			HamburgerBreadFood = config.get("HealAmount", "CheesePiece", 1).getInt();
			BottleWaterFood = config.get("HealAmount", "BottleWater", 2).getInt();
			RawHamburgerMeatFood = config.get("HealAmount", "RawHamburgerMeat", 4).getInt();
			roastPumpkinFood = config.get("HealAmount", "roastPumpkin", 7).getInt();
			HamburgerMeatFood = config.get("HealAmount", "HamburgerMeat", 6).getInt();
			RawBaconFood = config.get("HealAmount", "RawBacon", 2).getInt();
			BaconFood = config.get("HealAmount", "Bacon", 6).getInt();
			StripsFood = config.get("HealAmount", "Strips", 3).getInt();
			CheeseBaconBurgerFood = config.get("HealAmount", "CheeseBaconBurger", 16).getInt();
			CupChoklateFood = config.get("HealAmount", "CupChoklate", 6).getInt();
			friedEggFood = config.get("HealAmount", "friedEgg", 4).getInt();
			BreadSliceFood = config.get("HealAmount", "BreadSlice", 1).getInt();
			EggSandwichFood = config.get("HealAmount", "EggSandwich", 8).getInt();
			EggBaconSandwichFood = config.get("HealAmount", "EggBaconSandwich", 12).getInt();
			CupTeaFood = config.get("HealAmount", "CupTea", 6).getInt();
			HotDogRawFood = config.get("HealAmount", "HotDogRaw", 3).getInt();
			HotDogGrilledFood = config.get("HealAmount", "HotDogGrilled", 5).getInt();
			HotDogFood = config.get("HealAmount", "HotDog", 8).getInt();
			cornCobCookedFood = config.get("HealAmount", "cornCobCooked", 6).getInt();
			tomatoFood = config.get("HealAmount", "tomato", 1).getInt();
			HotDogKetchupFood = config.get("HealAmount", "HotDogKetchup", 11).getInt();
			PastaSalladFood = config.get("HealAmount", "PastaSallad", 10).getInt();
			PastaMeatsauceFood = config.get("HealAmount", "PastaMeatsauce", 12).getInt();
			ChickenSalladFood = config.get("HealAmount", "ChickenSallad", 10).getInt();
			CeasarSalladFood = config.get("HealAmount", "CeasarSallad", 10).getInt();
			MayonnaiseFood = config.get("HealAmount", "Mayonnaise", 2).getInt();
			MeatSauceFood = config.get("HealAmount", "MeatSauce", 4).getInt();
			MelonJuiceFood = config.get("HealAmount", "MelonJuice", 6).getInt();
			AppleJuiceFood = config.get("HealAmount", "AppleJuice", 6).getInt();
			BeefJerkyFood = config.get("HealAmount", "BeefJerky", 8).getInt();
			ChickenSandwichFood = config.get("HealAmount", "ChickenSandwich", 10).getInt();
			onionFood = config.get("HealAmount", "onion", 1).getInt();
			strawBerryFood = config.get("HealAmount", "strawBerry", 1).getInt();
			raspBerryFood = config.get("HealAmount", "raspBerry", 1).getInt();
			grapesFood = config.get("HealAmount", "grapes", 1).getInt();
			paltFood = config.get("HealAmount", "palt", 10).getInt();
			pancakesFood = config.get("HealAmount", "pancakes", 14).getInt();
			beerFood = config.get("HealAmount", "beer", 6).getInt();
			whiteWineFood = config.get("HealAmount", "whiteWine", 8).getInt();
			redWineFood = config.get("HealAmount", "redWine", 8).getInt();
			ChristmasMustFood = config.get("HealAmount", "Christmas-must", 8).getInt();
			MakiFood = config.get("HealAmount", "Maki", 6).getInt();
			LaxSuchiFood = config.get("HealAmount", "LaxSuchi", 8).getInt();
			BowlOfRiceFood = config.get("HealAmount", "BowlOfRice", 6).getInt();
			dogFoodFood = config.get("HealAmount", "dogFood", 3).getInt();
			chocolateBarFood = config.get("HealAmount", "chocolateBar", 8).getInt();
			StrawBerryjamFood = config.get("HealAmount", "StrawBerryjam", 4).getInt();
			RaspBerryjamFood = config.get("HealAmount", "RaspBerryjam", 4).getInt();
			RaspBerryJuiceFood = config.get("HealAmount", "RaspBerryJuice", 6).getInt();
			StrawBerryJuiceFood = config.get("HealAmount", "StrawBerryJuice", 6).getInt();
			tomatoAndOnionSalladFood = config.get("HealAmount", "tomatoAndOnionSallad", 8).getInt();
			macaroniAndCheeseFood = config.get("HealAmount", "macaroniAndCheese", 12).getInt();
			porridgeFood = config.get("HealAmount", "porridge", 12).getInt();
			gingerBreadFood = config.get("HealAmount", "gingerBread", 6).getInt();
			candyCaneFood = config.get("HealAmount", "candycane", 6).getInt();
			carrotStewFood = config.get("HealAmount", "carrotStew", 6).getInt();
			beefStewFood = config.get("HealAmount", "Beef stew", 8).getInt();
			onionStewFood = config.get("HealAmount", "Onion stew", 6).getInt();
			beefSoupFood = config.get("HealAmount", "Beef soup", 8).getInt();

			cornPlantBlock = config.get(Configuration.CATEGORY_BLOCK, "cornPlant", 3000).getInt();
			yellowSeedlingBlock = config.get(Configuration.CATEGORY_BLOCK, "yellowSeedling", 3002).getInt();
			redSeedlingBlock = config.get(Configuration.CATEGORY_BLOCK, "redSeedling", 3003).getInt();
			tomatoPlantBlock = config.get(Configuration.CATEGORY_BLOCK, "tomatoPlant", 3004).getInt();
			appleBlock = config.get(Configuration.CATEGORY_BLOCK, "appleBlock", 3005).getInt();
			avacadoBlock = config.get(Configuration.CATEGORY_BLOCK, "avacadoBlock", 3006).getInt();
			orangeBlock = config.get(Configuration.CATEGORY_BLOCK, "orangeBlock", 3007).getInt();
			cocoaBlock = config.get(Configuration.CATEGORY_BLOCK, "cocoaBlock", 3008).getInt();
			ApplePieBlock = config.get(Configuration.CATEGORY_BLOCK, "ApplePie", 3009).getInt();
			TacoPieBlock = config.get(Configuration.CATEGORY_BLOCK, "TacoPie", 3010).getInt();
			ChocolateCakeBlock = config.get(Configuration.CATEGORY_BLOCK, "ChocolateCake", 3011).getInt();
			MeatPieBlock = config.get(Configuration.CATEGORY_BLOCK, "MeatPie", 3012).getInt();
			saltBlock = config.get(Configuration.CATEGORY_BLOCK, "saltBlock", 3013).getInt();
			cheeseBlock = config.get(Configuration.CATEGORY_BLOCK, "cheeseBlock", 3014).getInt();
			BakeTableBlock = config.get(Configuration.CATEGORY_BLOCK, "BakeTableBlock", 3015).getInt();
			onionPlantBlock = config.get(Configuration.CATEGORY_BLOCK, "onionPlant", 3017).getInt();
			raspBerryPlantBlock = config.get(Configuration.CATEGORY_BLOCK, "raspBerryPlant", 3018).getInt();
			strawBerryPlantBlock = config.get(Configuration.CATEGORY_BLOCK, "strawBerryPlant", 3019).getInt();
			GrapeHolderBlock = config.get(Configuration.CATEGORY_BLOCK, "GrapeHolder", 3020).getInt();
			grapesPlantBlock = config.get(Configuration.CATEGORY_BLOCK, "grapesPlant", 3021).getInt();
			beerKegBlockID = config.get(Configuration.CATEGORY_BLOCK, "beerKegBlockID", 3022).getInt();
			wasabiPlantBlock = config.get(Configuration.CATEGORY_BLOCK, "wasabiPlant", 3023).getInt();
			Saplings = config.get(Configuration.CATEGORY_BLOCK, "Saplings", 3024).getInt();
			ricePlantBlock = config.get(Configuration.CATEGORY_BLOCK, "ricePlant", 3025).getInt();
			lettucePlantBlock = config.get(Configuration.CATEGORY_BLOCK, "lettucePlant", 3026).getInt();
			leavesBlock = config.get(Configuration.CATEGORY_BLOCK, "leaves", 3027).getInt();
			PlateBlock = config.get(Configuration.CATEGORY_BLOCK, "plate", 3028).getInt();
			shelfBlock = config.get(Configuration.CATEGORY_BLOCK, "shelf", 3029).getInt();
//			presentBlock = config.get(config.CATEGORY_BLOCK, "present", 3030).getInt();
			
			tomatoSeedsID = config.get(Configuration.CATEGORY_ITEM, "tomatoSeeds", 3397).getInt();
			cornSeedsID = config.get(Configuration.CATEGORY_ITEM, "cornSeeds", 3398).getInt();
			pumpkinPieceID = config.get(Configuration.CATEGORY_ITEM, "pumpkinPiece", 3400).getInt();
			roastPumpkinID = config.get(Configuration.CATEGORY_ITEM, "roastPumpkin", 3401).getInt();
			lettuceSeedsID = config.get(Configuration.CATEGORY_ITEM, "lettuceSeeds", 3402).getInt();
			cornCobID = config.get(Configuration.CATEGORY_ITEM, "cornCob", 3403).getInt();
			yellowSeedsID = config.get(Configuration.CATEGORY_ITEM, "yellowSeeds", 3405).getInt();
			redSeedsID = config.get(Configuration.CATEGORY_ITEM, "redSeeds", 3406).getInt();
			cornCobCookedID = config.get(Configuration.CATEGORY_ITEM, "cornCobCooked", 3407).getInt();
			tomatoID = config.get(Configuration.CATEGORY_ITEM, "tomato", 3408).getInt();
			lettuceID = config.get(Configuration.CATEGORY_ITEM, "lettuce", 3410).getInt();
			orangeID = config.get(Configuration.CATEGORY_ITEM, "orange", 3411).getInt();
			cocoaID = config.get(Configuration.CATEGORY_ITEM, "cocoa", 3412).getInt();
			avacadoID = config.get(Configuration.CATEGORY_ITEM, "avacado", 3413).getInt();
			orangeJuiceID = config.get(Configuration.CATEGORY_ITEM, "orangeJuice", 3414).getInt();
			DollarID = config.get(Configuration.CATEGORY_ITEM, "Dollar", 3415).getInt();
			HamBurgerID = config.get(Configuration.CATEGORY_ITEM, "HamBurger", 3416).getInt();
			CheeseBurgerID = config.get(Configuration.CATEGORY_ITEM, "CheeseBurger", 3417).getInt();
			CheeseMoldID = config.get(Configuration.CATEGORY_ITEM, "CheeseMold", 3418).getInt();
			CheeseMoldMilkID = config.get(Configuration.CATEGORY_ITEM, "CheeseMoldMilk", 3419).getInt();
			CheeseMoldCheeseID = config.get(Configuration.CATEGORY_ITEM, "CheeseMoldCheese", 3420).getInt();
			CheeseBlockID = config.get(Configuration.CATEGORY_ITEM, "CheeseBlock", 3421).getInt();
			CheesePieceID = config.get(Configuration.CATEGORY_ITEM, "CheesePiece", 3422).getInt();
			HamburgerBreadID = config.get(Configuration.CATEGORY_ITEM, "HamburgerBread", 3423).getInt();
			BottleWaterID = config.get(Configuration.CATEGORY_ITEM, "BottleWater", 3424).getInt();
			DrinkingGlassID = config.get(Configuration.CATEGORY_ITEM, "DrinkingGlass", 3425).getInt();
			KnifeID = config.get(Configuration.CATEGORY_ITEM, "Knife", 3426).getInt();
			RawHamburgerMeatID = config.get(Configuration.CATEGORY_ITEM, "RawHamburgerMeat", 3427).getInt();
			HamburgerMeatID = config.get(Configuration.CATEGORY_ITEM, "HamburgerMeat", 3428).getInt();
			RawBaconID = config.get(Configuration.CATEGORY_ITEM, "RawBacon", 3429).getInt();
			BaconID = config.get(Configuration.CATEGORY_ITEM, "Bacon", 3430).getInt();
			StripsID = config.get(Configuration.CATEGORY_ITEM, "Strips", 3431).getInt();
			CheeseBaconBurgerID = config.get(Configuration.CATEGORY_ITEM, "CheeseBaconBurger", 3432).getInt();
			CupUnburnedID = config.get(Configuration.CATEGORY_ITEM, "CupUnburned", 3433).getInt();
			CupID = config.get(Configuration.CATEGORY_ITEM, "Cup", 3434).getInt();
			CupChoklateID = config.get(Configuration.CATEGORY_ITEM, "CupChoklate", 3435).getInt();
			TeaCanUnburnedID = config.get(Configuration.CATEGORY_ITEM, "TeaCanUnburned", 3436).getInt();
			TeaCanID = config.get(Configuration.CATEGORY_ITEM, "TeaCan", 3437).getInt();
			friedEggID = config.get(Configuration.CATEGORY_ITEM, "friedEgg", 3438).getInt();
			BreadSliceID = config.get(Configuration.CATEGORY_ITEM, "BreadSlice", 3439).getInt();
			EggSandwichID = config.get(Configuration.CATEGORY_ITEM, "EggSandwich", 3440).getInt();
			EggBaconSandwichID = config.get(Configuration.CATEGORY_ITEM, "EggBaconSandwich", 3441).getInt();
			CupTeaID = config.get(Configuration.CATEGORY_ITEM, "CupTea", 3442).getInt();
			ColdTeaCanID = config.get(Configuration.CATEGORY_ITEM, "ColdTeaCan", 3443).getInt();
			HotTeaCanID = config.get(Configuration.CATEGORY_ITEM, "HotTeaCan", 3444).getInt();
			HotDogRawID = config.get(Configuration.CATEGORY_ITEM, "HotDogRaw", 3445).getInt();
			HotDogGrilledID = config.get(Configuration.CATEGORY_ITEM, "HotDogGrilled", 3446).getInt();
			HotDogID = config.get(Configuration.CATEGORY_ITEM, "HotDog", 3447).getInt();
			BucketID = config.get(Configuration.CATEGORY_ITEM, "Bucket", 3455).getInt();
			bucketWaterID = config.get(Configuration.CATEGORY_ITEM, "bucketWater", 3456).getInt();
			bucketMilkID = config.get(Configuration.CATEGORY_ITEM, "bucketMilk", 3457).getInt();
			obsidianPickID = config.get(Configuration.CATEGORY_ITEM, "obsidianPick", 3458).getInt();
			obsidianShovelID = config.get(Configuration.CATEGORY_ITEM, "obsidianShovel", 3459).getInt();
			obsidianAxeID = config.get(Configuration.CATEGORY_ITEM, "obsidianAxe", 3460).getInt();
			obsidianHoeID = config.get(Configuration.CATEGORY_ITEM, "obsidianHoe", 3461).getInt();
			obsidianSwordID = config.get(Configuration.CATEGORY_ITEM, "obsidianSword", 3462).getInt();
			guacamoleID = config.get(Configuration.CATEGORY_ITEM, "guacamole", 3463).getInt();
			applesnufkinID = config.get(Configuration.CATEGORY_ITEM, "applesnufkin", 3464).getInt();
			orangecoresID = config.get(Configuration.CATEGORY_ITEM, "orangecores", 3465).getInt();
			avacadonutID = config.get(Configuration.CATEGORY_ITEM, "avacadonut", 3466).getInt();
			ApplePieID = config.get(Configuration.CATEGORY_ITEM, "ApplePie", 3467).getInt();
			TacoPieID = config.get(Configuration.CATEGORY_ITEM, "TacoPie", 3468).getInt();
			ChocolateCakeID = config.get(Configuration.CATEGORY_ITEM, "ChocolateCake", 3469).getInt();
			MeatPieID = config.get(Configuration.CATEGORY_ITEM, "MeatPie", 3470).getInt();
			AppleJuiceID = config.get(Configuration.CATEGORY_ITEM, "AppleJuice", 3471).getInt();
			SaltID = config.get(Configuration.CATEGORY_ITEM, "Salt", 3472).getInt();
			PastaID = config.get(Configuration.CATEGORY_ITEM, "Pasta", 3473).getInt();
			KetchupID = config.get(Configuration.CATEGORY_ITEM, "Ketchup", 3474).getInt();
			PastaMeatsauceID = config.get(Configuration.CATEGORY_ITEM, "PastaMeatsauce", 3475).getInt();
			ChickenSalladID = config.get(Configuration.CATEGORY_ITEM, "ChickenSallad", 3476).getInt();
			HotDogKetchupID = config.get(Configuration.CATEGORY_ITEM, "HotDogKetchup", 3477).getInt();
			MeatSauceID = config.get(Configuration.CATEGORY_ITEM, "MeatSauce", 3478).getInt();
			BeefJerkyID = config.get(Configuration.CATEGORY_ITEM, "BeefJerky", 3479).getInt();
			ChickenSandwichID = config.get(Configuration.CATEGORY_ITEM, "ChickenSandwich", 3480).getInt();
			CeasarSalladID = config.get(Configuration.CATEGORY_ITEM, "CeasarSallad", 3481).getInt();
			MayonnaiseID = config.get(Configuration.CATEGORY_ITEM, "Mayonnaise", 3482).getInt();
			OilID = config.get(Configuration.CATEGORY_ITEM, "Oil", 3483).getInt();
			MelonJuiceID = config.get(Configuration.CATEGORY_ITEM, "MelonJuice", 3484).getInt();
			PastaSalladID = config.get(Configuration.CATEGORY_ITEM, "PastaSallad", 3485).getInt();
			riceSeedsID = config.get(Configuration.CATEGORY_ITEM, "riceSeeds", 3486).getInt();
			RiceID = config.get(Configuration.CATEGORY_ITEM, "Rice", 3487).getInt();
			WasabiRootID = config.get(Configuration.CATEGORY_ITEM, "WasabiRoot", 3488).getInt();
			onionID = config.get(Configuration.CATEGORY_ITEM, "onion", 3490).getInt();
			strawBerryID = config.get(Configuration.CATEGORY_ITEM, "strawBerry", 3491).getInt();
			raspBerryID = config.get(Configuration.CATEGORY_ITEM, "raspBerry", 3492).getInt();
			grapesID = config.get(Configuration.CATEGORY_ITEM, "grapes", 3493).getInt();
			paltID = config.get(Configuration.CATEGORY_ITEM, "palt", 3494).getInt();
			pancakesID = config.get(Configuration.CATEGORY_ITEM, "pancakes", 3495).getInt();
			onionSeedsID = config.get(Configuration.CATEGORY_ITEM, "onionSeeds", 3497).getInt();
			raspBerrySeedsID = config.get(Configuration.CATEGORY_ITEM, "raspBerrySeeds", 3498).getInt();
			strawBerrySeedsID = config.get(Configuration.CATEGORY_ITEM, "strawBerrySeeds", 3499).getInt();
			grapeSeedsID = config.get(Configuration.CATEGORY_ITEM, "grapeSeeds", 3500).getInt();
			beerCupID = config.get(Configuration.CATEGORY_ITEM, "beerCup", 3501).getInt();
			beerID = config.get(Configuration.CATEGORY_ITEM, "beer", 3502).getInt();
			redWineID = config.get(Configuration.CATEGORY_ITEM, "redWine", 3503).getInt();
			whiteWineID = config.get(Configuration.CATEGORY_ITEM, "whiteWine", 3504).getInt();
			beerBaseID = config.get(Configuration.CATEGORY_ITEM, "beerBase", 3505).getInt();
			redWineBaseID = config.get(Configuration.CATEGORY_ITEM, "redWineBase", 3506).getInt();
			whiteWineBaseID = config.get(Configuration.CATEGORY_ITEM, "whiteWineBase", 3507).getInt();
			MakiLongID = config.get(Configuration.CATEGORY_ITEM, "MakiLong", 3508).getInt();
			MakiShortID = config.get(Configuration.CATEGORY_ITEM, "MakiShort", 3509).getInt();
			LaxSuchiID = config.get(Configuration.CATEGORY_ITEM, "LaxSuchi", 3510).getInt();
			BowlOfRiceID = config.get(Configuration.CATEGORY_ITEM, "BowlOfRice", 3511).getInt();
			dogFoodID = config.get(Configuration.CATEGORY_ITEM, "dogFood", 3512).getInt();
			WasabiID = config.get(Configuration.CATEGORY_ITEM, "Wasabi", 3513).getInt();
			jamJarID = config.get(Configuration.CATEGORY_ITEM, "jamJar", 3514).getInt();
			RaspBerryjamID = config.get(Configuration.CATEGORY_ITEM, "RaspBerryjam", 3515).getInt();
			StrawBerryjamID = config.get(Configuration.CATEGORY_ITEM, "StrawBerryjam", 3516).getInt();
			chocolateBarID = config.get(Configuration.CATEGORY_ITEM, "chocolateBar", 3517).getInt();
			RaspBerryJuiceID = config.get(Configuration.CATEGORY_ITEM, "RaspBerryJuice", 3519).getInt();
			StrawBerryJuiceID = config.get(Configuration.CATEGORY_ITEM, "StrawBerryJuice", 3520).getInt();
			tomatoAndOnionSalladID = config.get(Configuration.CATEGORY_ITEM, "tomatoAndOnionSallad", 3521).getInt();
			macaroniAndCheeseID = config.get(Configuration.CATEGORY_ITEM, "macaroniAndCheese", 3522).getInt();
			porridgeID = config.get(Configuration.CATEGORY_ITEM, "porridge", 3523).getInt();
			MaltID = config.get(Configuration.CATEGORY_ITEM, "Malt", 3524).getInt();
			wasabiSeedsID = config.get(Configuration.CATEGORY_ITEM, "wasabiSeeds", 3525).getInt();
			boiledRiceID = config.get(Configuration.CATEGORY_ITEM, "boiledRice", 3527).getInt();
			tallBottleID = config.get(Configuration.CATEGORY_ITEM, "tallbottle", 3528).getInt();
			ChristmasMustID = config.get(Configuration.CATEGORY_ITEM, "Christmas-must", 3529).getInt();
			ChristmasMustBaseID = config.get(Configuration.CATEGORY_ITEM, "Christmas-must base", 3530).getInt();
			gingerBreadID = config.get(Configuration.CATEGORY_ITEM, "gingerBread", 3532).getInt();
			candyCaneID = config.get(Configuration.CATEGORY_ITEM, "candycane", 3533).getInt();
			carrotStewID = config.get(Configuration.CATEGORY_ITEM, "carrotStew", 3534).getInt();
			forkID = config.get(Configuration.CATEGORY_ITEM, "Fork", 3535).getInt();
			beefStewID = config.get(Configuration.CATEGORY_ITEM, "Beef stew", 3536).getInt();
			onionStewID = config.get(Configuration.CATEGORY_ITEM, "Onion stew", 3537).getInt();
			beefSoupID = config.get(Configuration.CATEGORY_ITEM, "Beef soup", 3538).getInt();
	}
}
