package v3XzZ.mFC.lib;

import net.minecraft.item.Item;

public class Items {

	public static Item money;
	public static Item hamburgerOrginal;
	public static Item hamburgerCheese;
	public static Item moldEmpty;
	public static Item moldMilk;
	public static Item moldCheese;
	public static Item cheeseWheel;
	public static Item cheesePiece;
	public static Item hamburgerBread;
	public static Item glassWater;
	public static Item drinkingGlass;
	public static Item Knife;
	public static Item hamburgerRaw;
	public static Item hamburger;
	public static Item baconRaw;
	public static Item bacon;
	public static Item frenchFries;
	public static Item hamburgerBacon;
	public static Item clayCup;
	public static Item cup;
	public static Item cupChocolate;
	public static Item clayTeapot;
	public static Item teapot;
	public static Item friedEgg;
	public static Item breadSlice;
	public static Item sandwichEgg;
	public static Item sandwichBacon;
	public static Item cupTea;
	public static Item teapotCold;
	public static Item teapotHot;
	public static Item sausageRaw;
	public static Item sausage;
	public static Item hotDog;
	public static Item glassAppleJuice;
	public static Item glassMelonJuice;
	public static Item saltPile;
	public static Item pasta;
	public static Item bottleOfKetchup;
	public static Item pastaMeat;
	public static Item saladChicken;
	public static Item hotDogKetchup;
	public static Item meatScrap;
	public static Item beefJerky;
	public static Item sandwichChicken;
	public static Item saladCeasar;
	public static Item mayonnaise;
	public static Item bottleOfOil;
	public static Item saladPasta;
	public static Item wasabiRoot;
	public static Item onion;
	public static Item strawBerry;
	public static Item raspBerry;
	public static Item grapes;
	public static Item palt;
	public static Item porridge;
	public static Item creamIron;
	public static Item creamWood;
	public static Item butter;
	public static Item tomatoStew;
	public static Item potatoSallad;
	public static Item StrawBerryjam;
	public static Item RaspBerryjam;
	public static Item jamJar;
	public static Item glassRaspBerryJuice;
	public static Item glassStrawBerryJuice;
	public static Item pancake;
	public static Item chocolateBar;
	public static Item dogFood;
	public static Item carrotStew;
	public static Item beefStew;
	public static Item onionStew;
	public static Item beefSoup;
	public static Item MakiLong;
	public static Item MakiShort;
	public static Item LaxSuchi;
	public static Item wasabi;
	public static Item bowlOfRice;
	public static Item malt;
	public static Item macaroniAndCheese;
	public static Item boiledRice;
	public static Item beerCup;
	public static Item beer;
	public static Item redWine;
	public static Item whiteWine;
	public static Item tallBottle;
	public static Item christmasMust;
	public static Item beerBase;
	public static Item redWineBase;
	public static Item whiteWineBase;
	public static Item christmasMustBase;
	public static Item gingerBread;
	public static Item candyCane;
	//Buckets
	public static Item woodenBucket;
	public static Item woodenBucketWater;
	public static Item woodenBucketMilk;
	
	//Pies
	public static Item itemApplePie;
	public static Item itemTacoPie;
	public static Item itemChocolateCake;
	public static Item itemMeatPie;
	
	//Tools
	public static Item obsidianPick;
	public static Item obsidianShovel;
	public static Item obsidianAxe;
	public static Item obsidianHoe;
	public static Item obsidianSword;
	
	public static Item pumpkinPiece;
	public static Item roastPumpkin;
	public static Item redSeeds;
	public static Item yellowSeeds;
	public static Item tomatoSeeds;
	public static Item cornSeeds;
	public static Item cottonSeeds;
	public static Item lettuceSeeds;
	public static Item onionSeeds;
	public static Item raspBerrySeeds;
	public static Item strawBerrySeeds;
	public static Item wasabiSeeds;
	public static Item cornCob;
	public static Item cornCobCooked;
	public static Item tomato;
	public static Item lettuce;
	public static Item orange;
	public static Item CocoaFruit;
	public static Item guacamole;
	public static Item avacado;
	public static Item orangeJuice;
	public static Item AvacadoSeeds;
	public static Item OrangeSeeds;
	public static Item AppleSeeds;
	public static Item riceSeeds;
	public static Item Rice;
	public static Item grapeSeeds;
	
	public static Item fork;

}
